trigger:
  branches:
   include:
     - master
  paths:
    exclude:
      - azure-pipelines.yml
      - azure-pipelines-docker.yml
  
pool: 'Own'

variables:
  buildConfiguration: 'Release'

steps:
- task: Docker@2
  displayName: "Image bauen"  
  inputs:
    containerRegistry: 'Dokcer HUB'
    repository: 'mtjr/hardwaremonitor'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.SourceBranchName)-$(Build.BuildId)
  condition: succeeded()


- task: Docker@2
  displayName: "Image pushen"  
  inputs:
    containerRegistry: 'Dokcer HUB'
    repository: 'mtjr/hardwaremonitor'
    command: 'push'
    tags: |
      latest
      $(Build.SourceBranchName)-$(Build.BuildId)
  condition: succeeded()
