version: '2'
services:
  postgres:
    image: postgres:12.4
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: hardwaremonitor
      POSTGRES_USER: admin
    volumes:
      - postgres:/var/lib/postgresql/data

  hardwaremonitor:
    container_name: hardwaremonitor
    hostname: hardwaremonitor
    image: mtjr/hardwaremonitor
    restart: always
    ports:
      - "5000:5000"
    links:
      - postgres
    environment: 
      - ASPNETCORE_URLS=http://*:5000     
      - HardwareMonitorConfiguration__DatabaseConnectionString=Server=postgres;Port=5432;Database=hardwaremonitor;User Id=admin;Password=hardwaremonitor 

volumes:
  postgres:      